#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso MPPICTurbulenceModels

wclean
#wclean MPPICDyMFoam
#wclean MPPICDyMFoam/MPPICDyMFoam

#------------------------------------------------------------------------------
